######################################################################
# Automatically generated by qmake (2.01a) Tue Sep 23 15:09:42 2025
######################################################################

TEMPLATE = app
TARGET = Machinimaker
DEPENDPATH += . \
              build/Desktop-Debug/machinimaker_autogen \
              build/Desktop-Release/machinimaker_autogen \
              build/Desktop-Debug/machinimaker_autogen/EWIEGA46WW \
              build/Desktop-Debug/machinimaker_autogen/include \
              build/Desktop-Release/machinimaker_autogen/EWIEGA46WW \
              build/Desktop-Release/machinimaker_autogen/include \
              build/Desktop-Debug/CMakeFiles/3.31.8/CompilerIdCXX \
              build/Desktop-Release/CMakeFiles/3.31.8/CompilerIdCXX
INCLUDEPATH += . \
               build/Desktop-Debug/machinimaker_autogen/include \
               build/Desktop-Debug/machinimaker_autogen/EWIEGA46WW
QT+= widgets
QT+= gui
QT+=core

# Input
HEADERS += machinimaker.h \
           help.h \
           message.h \
           messagedialog.h \
           messagequeue.h \
           queuemodel.h \
           queuewindow.h 
FORMS += machinimaker.ui MessageDialog.ui QueueWindow.ui \
    help.ui
SOURCES += machinimaker.cpp \
           help.cpp \
           main.cpp \
           messagedialog.cpp \
           messagequeue.cpp \
           queuewindow.cpp 
RESOURCES += appIcons.qrc
TRANSLATIONS += machinimaker_en_US.ts
